# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dVZR7BG_oR04lZ72UlLhdCZ-2-U1hSbp
"""

# Oddiy kalkulyator
def kalkulyator():
    print("Oddiy Kalkulyator")
    print("1. Qo'shish")
    print("2. Ayirish")
    print("3. Ko'paytirish")
    print("4. Bo'lish")

    tanlov = input("Amal tanlang (1/2/3/4): ")

    if tanlov in ['1', '2', '3', '4']:
        son1 = float(input("Birinchi sonni kiriting: "))
        son2 = float(input("Ikkinchi sonni kiriting: "))

        if tanlov == '1':
            print(f"Natija: {son1} + {son2} = {son1 + son2}")
        elif tanlov == '2':
            print(f"Natija: {son1} - {son2} = {son1 - son2}")
        elif tanlov == '3':
            print(f"Natija: {son1} * {son2} = {son1 * son2}")
        elif tanlov == '4':
            if son2 != 0:
                print(f"Natija: {son1} / {son2} = {son1 / son2}")
            else:
                print("Bo'lish amali uchun son nol bo'lishi mumkin emas!")
    else:
        print("Noto'g'ri tanlov. Qayta urinib ko'ring.")

# Funksiyani ishga tushirish
kalkulyator()